SET search_path TO 'v3';

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE v3.app_config (
    config_group text NOT NULL PRIMARY KEY,
    value json NOT NULL
);

CREATE TABLE v3.app_counter (
    version integer PRIMARY KEY,
    count integer
);

CREATE TABLE v3.app_update (
    version integer PRIMARY KEY,
    url text NOT NULL,
    force boolean NOT NULL,
    checksum text NOT NULL,
    changelog text NOT NULL
);

CREATE TABLE v3.users (
    id uuid DEFAULT uuid_generate_v4 () PRIMARY KEY,
    useraddress text[] NOT NULL,
    accounttype text NOT NULL,
    smartcard boolean NOT NULL
);

CREATE TABLE v3.vpn_keys (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key text NOT NULL,
    validity integer NOT NULL,
    used boolean,
    user_id uuid,
    txhash text,
    with_pro boolean,
    timestamp timestamp without time zone
);

ALTER TABLE v3.vpn_keys
    ADD FOREIGN KEY ("user_id") REFERENCES users ("id");
